### PR TITLE
fix(SvgCanvas): allow canvas size modification

### LINKED ISSUE #927: Height setting doesn't work after creating an SvgCanvas
It works for Canvas 
```
const canvas = createCanvas(containerWidth, 0) 
canvas.height = 400 // fine, the height of rendered image is 400
```
    
But for SvgCanvas setter does not work
```
const canvas = createCanvas(containerWidth, 0, SvgExportFlag.ConvertTextToPaths) 
canvas.height = 400 // doesn't work, the height is default 150
```

Can we add a setter to SvgCanvas to match Canvas api?

### PR DESCRIPTION
**Pull request by twlite**
closes #927

### CODE REVIEW

File: src/path.rs [hunk 1]
```diff
@@ -298,7 +298,7 @@ impl Path {
   #[napi(js_name = "toSVGString")]
   pub fn to_svg_string(&self, env: Env) -> Result<JsString> {
     let sk_string = self.inner.to_svg_string();
-    unsafe { env.create_string_from_c_char(sk_string.ptr, sk_string.length) }
+    unsafe { env.create_string_from_c_char(sk_string.ptr, sk_string.length as isize) }
```
Comment (twlite) [inline src/path.rs:301]: It doesn't build without this

**Comment by twlite** [comment]
@Brooooooklyn i'm so sorry there's some issue in this 😓 
this is not creating svg context I'll make another pr.
